name: orangepi-zero2w

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
            submodules: true

      - name: Install Software
        run: |
              sudo apt-get update && \
              sudo apt-get install -y build-essential gcc-aarch64-linux-gnu device-tree-compiler \
                                      libgnutls28-dev sunxi-tools

      - name: Compile U-Boot
        run: |
              bash build.sh

      - name: Upload U-Boot Artifact
        uses: actions/upload-artifact@v4
        with:
          name: orangepi-uboot
          path: u-boot/u-boot-sunxi-with-spl.bin
          retention-days: 30

      - name: Upload fel-sdboot.sunxi Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fel-sdboot.sunxi
          path: /usr/share/sunxi-tools/fel-sdboot.sunxi
          retention-days: 30

